defaults:
  - algorithm/ppo
  - architecture/rnn
  - ued/alp_gmm
  - plr/default
  - logging/default
  - car_racing/default
  - override hydra/launcher: submitit_local

# Fine-tuning arguments
xpid_finetune: False
model_finetune: model

# Hardware arguments
no_cuda: False

# Evaluation arguments
test_interval: 250
test_num_episodes: 10
test_num_processes: 2
test_env_names:
  - BipedalWalker-v3
  - BipedalWalkerHardcore-v3
  - BipedalWalker-Med-Stairs-v0
  - BipedalWalker-Med-PitGap-v0
  - BipedalWalker-Med-StumpHeight-v0
  - BipedalWalker-Med-Roughness-v0

# Environment arguments
env_name: BipedalWalker-Adversarial-v0
handle_timelimits: True
singleton_env: False
use_global_critic: False
use_global_policy: False

# Override algo values
algorithm:
  lr: 0.0003
  max_grad_norm: 0.5
  gae_lambda: 0.9
  gamma: 0.99
  value_loss_coef: 0.5
  entropy_coef: 0.001
  adv_entropy_coef: 0.01
  clip_value_loss: False
  clip_param: 0.2
  reward_shaping: True
  use_categorical_adv: True
  use_skip: False
  choose_start_pos: False
  sparse_rewards: False
  adv_max_grad_norm: 0.5
  adv_ppo_epoch: 8
  adv_num_mini_batch: 4
  adv_normalize_returns: False
  adv_use_popart: False
  num_processes: 16
  num_env_steps: 2000000000
  num_steps: 2048
  ppo_epoch: 5
  num_mini_batch: 32
  normalize_returns: True

architecture:
  recurrent_agent: False
  recurrent_adversary_env: False
  recurrent_hidden_size: 1

plr:
  use_plr: False

logging:
  log_dir: ~/logs/dcd/bipedal/alpgmm
  log_interval: 10
  test_interval: 100
  test_num_episodes: 10
  test_num_processes: 2
  screenshot_interval: 200
  log_plr_buffer_stats: True
  log_replay_complexity: True
  checkpoint: True
  log_action_complexity: False
  log_grad_norm: True
  checkpoint_basis: student_grad_updates
  archive_interval: 5000