# @package _global_
defaults:
  - algorithm/ppo
  - architecture/rnn
  - ued/paired
  - plr/default
  - logging/default
  - car_racing/default
  - override hydra/launcher: submitit_local

callbacks:
  algorithm:
    lr: 0.003

# Fine-tuning arguments
xpid_finetune: False
model_finetune: model

# Hardware arguments
no_cuda: False

# Evaluation arguments
test_interval: 250
test_num_episodes: 10
test_num_processes: 2
test_env_names:
  - BipedalWalker-v3
  - BipedalWalkerHardcore-v3
  - BipedalWalker-Med-Stairs-v0
  - BipedalWalker-Med-PitGap-v0
  - BipedalWalker-Med-StumpHeight-v0
  - BipedalWalker-Med-Roughness-v0

# Environment arguments
env_name: BipedalWalker-Adversarial-Easy-v0
handle_timelimits: False
singleton_env: False
use_global_critic: False
use_global_policy: False